// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqnS-_VfiEZjBkhvU3HvqpuYogwZQLF7g',
    appId: '1:161599788025:web:402390ffac332388cbe328',
    messagingSenderId: '161599788025',
    projectId: 'flutter-aula-virtual-app',
    authDomain: 'flutter-aula-virtual-app.firebaseapp.com',
    storageBucket: 'flutter-aula-virtual-app.firebasestorage.app',
    measurementId: 'G-2582PGDSPB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_rmKhXwN8ais8UTNXe2ycYd9fW0OypNQ',
    appId: '1:161599788025:android:ae663a16ca9c9eedcbe328',
    messagingSenderId: '161599788025',
    projectId: 'flutter-aula-virtual-app',
    storageBucket: 'flutter-aula-virtual-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXLzImxdVUrQcKkXzLzY4LayPh2NI9sEs',
    appId: '1:161599788025:ios:33409f2de7725bcdcbe328',
    messagingSenderId: '161599788025',
    projectId: 'flutter-aula-virtual-app',
    storageBucket: 'flutter-aula-virtual-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterAulaVirtualApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXLzImxdVUrQcKkXzLzY4LayPh2NI9sEs',
    appId: '1:161599788025:ios:33409f2de7725bcdcbe328',
    messagingSenderId: '161599788025',
    projectId: 'flutter-aula-virtual-app',
    storageBucket: 'flutter-aula-virtual-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterAulaVirtualApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqnS-_VfiEZjBkhvU3HvqpuYogwZQLF7g',
    appId: '1:161599788025:web:834fd63784a7b5d0cbe328',
    messagingSenderId: '161599788025',
    projectId: 'flutter-aula-virtual-app',
    authDomain: 'flutter-aula-virtual-app.firebaseapp.com',
    storageBucket: 'flutter-aula-virtual-app.firebasestorage.app',
    measurementId: 'G-CGRK5K0860',
  );
}
